#pragma once


#define CHARACTE_CREATE_TIME 7.f
#define ENEMY_CHARACTE_CREATE_TIME 5.f
#define BULLET_CREATE_TIME 3.f

#define BUILDING_SIZE 100.f
#define CHARACTER_SIZE 10.f
#define BULLET_SIZE 2.f
#define ARROW_SIZE 2.f

#define BUILDING_LIFE 500
#define BUILDING_SPEED 0
#define CHARACTER_LIFE 10
#define CHARACTER_SPEED 300
#define BULLET_LIFE 20
#define BULLET_SPEED 600
#define ARROW_LIFE 10
#define ARROW_SPEED 100