#pragma once


#define CHARACTE_CREATE_TIME		7.f
#define ENEMY_CHARACTE_CREATE_TIME	5.f
#define BULLET_CREATE_TIME			3.f

#define BUILDING_SIZE	100.f
#define CHARACTER_SIZE	50.f
#define BULLET_SIZE		4.f
#define ARROW_SIZE		4.f

#define BUILDING_LIFE	500
#define BUILDING_SPEED	0

#define CHARACTER_LIFE	10
#define CHARACTER_SPEED 100

#define BULLET_LIFE		20
#define BULLET_SPEED	100

#define ARROW_LIFE		10
#define ARROW_SPEED		100